//
// Created by yifei on 5/6/18.
//

#ifndef DVRK_OPENGLVIEWER_ROSCAMERAINFOPROVIDER_H
#define DVRK_OPENGLVIEWER_ROSCAMERAINFOPROVIDER_H


class ROSCameraInfoProvider {

};


#endif //DVRK_OPENGLVIEWER_ROSCAMERAINFOPROVIDER_H
